"""Generates the four TARS/Skills/_Registry/*.md notes (Phase 9). These
files are always overwritten wholesale on sync -- never hand-edited, so a
generation banner marks that clearly.
"""
from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

_GENERATED_BANNER = (
    "> [!warning] Auto-generated\n"
    "> This note is regenerated by TARS's skill registry sync. Manual edits will be overwritten.\n\n"
)


def render_skill_catalog_note(summary: dict[str, Any]) -> str:
    lines = [_GENERATED_BANNER, "# Skill Catalog\n"]
    lines.append(f"- **Total catalog records:** {summary['total_records']}")
    lines.append(f"- **Trusted records:** {summary['trusted_records']}")
    lines.append(f"- **Community records:** {summary['community_records']}")
    lines.append(f"- **Installed count:** {summary['installed_count']}")
    lines.append("")
    lines.append("## Sources\n")
    lines.append("| Source | Records | Last synced |")
    lines.append("|---|---|---|")
    for src in summary["sources"]:
        lines.append(f"| {src['source']} | {src['record_count']} | {src.get('last_synced_at') or '-'} |")
    return "\n".join(lines) + "\n"


def render_installed_skills_note(installed: list[dict[str, Any]]) -> str:
    lines = [_GENERATED_BANNER, "# Installed Skills\n"]
    if not installed:
        lines.append("_No skills installed yet._\n")
        return "\n".join(lines)

    by_category: dict[str, list[dict[str, Any]]] = {}
    for skill in installed:
        by_category.setdefault(skill["category"], []).append(skill)

    for category in sorted(by_category):
        lines.append(f"## {category}\n")
        for skill in sorted(by_category[category], key=lambda s: s["name"]):
            lines.append(f"### {skill['name']}")
            lines.append(f"- **Identifier:** `{skill['identifier']}`")
            lines.append(f"- **Description:** {skill.get('description', '')}")
            lines.append(f"- **Source:** {skill.get('source') or 'unknown'}")
            lines.append(f"- **Trust:** {skill.get('trust_level') or 'unknown'}")
            lines.append(f"- **Content hash:** `{skill['content_hash'][:12]}...`")
            lines.append(f"- **Local path:** `{skill['local_path']}`")
            lines.append(f"- **Last update:** {skill['updated_at']}")
            lines.append("")
    return "\n".join(lines)


def render_sources_note(sources: list[dict[str, Any]]) -> str:
    lines = [_GENERATED_BANNER, "# Sources\n"]
    lines.append("| Source | Records | Last synced | Notes |")
    lines.append("|---|---|---|---|")
    for src in sources:
        lines.append(f"| {src['source']} | {src['record_count']} | {src.get('last_synced_at') or '-'} | {src.get('notes') or ''} |")
    return "\n".join(lines) + "\n"


def render_sync_status_note(last_sync: dict[str, Any] | None) -> str:
    lines = [_GENERATED_BANNER, "# Sync Status\n"]
    if last_sync is None:
        lines.append("_No successful sync recorded yet._\n")
        return "\n".join(lines)
    lines.append(f"- **Last successful sync:** {last_sync.get('finished_at')}")
    lines.append(f"- **Record count:** {last_sync.get('record_count')}")
    lines.append(f"- **Acquisition method:** {last_sync.get('acquisition_method')}")
    lines.append(f"- **Catalog URL:** {last_sync.get('catalog_url')}")
    lines.append(f"- **SHA-256:** `{last_sync.get('sha256')}`")
    lines.append(f"- **Duration:** {last_sync.get('duration_seconds')}s")
    if last_sync.get("error"):
        lines.append(f"- **Error:** {last_sync['error']}")
    return "\n".join(lines) + "\n"


def generated_timestamp() -> str:
    return datetime.now(UTC).isoformat()
